db:
  image: postgres
  restart: always

app:
  build: .
  expose:
    - "3000"
  links:
    - db:pw-db
  restart: always

web:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - app:pw-app
  volumes:
    - ./lib/nginx/ssl-certs/:/root/ssl-certs:ro
    - ./lib/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  restart: always
